export const SWIPER_EFFECT = {
	random: 'random',
	dots: 'dots',
	flyeye: 'flyeye',
	morphX: 'morph-x',
	morphY: 'morph-y',
	pageCurl: 'page-curl',
	peelX: 'peel-x',
	peelY: 'peel-y',
	polygonsFall: 'polygons-fall',
	polygonsMorph: 'polygons-morph',
	polygonsWind: 'polygons-wind',
	pixelize: 'pixelize',
	ripple: 'ripple',
	shutters: 'shutters',
	slices: 'slices',
	squares: 'squares',
	waveX: 'wave-x',
	wind: 'wind',
};
